"use client";
import{useEffect,useState}from"react";
type S={id:string;name:string;role:string};type E={id:string;title:string;description:string;importance:string};type T={id:string;event_time:string;title:string;description:string};
type Node={id:string;type:"suspect"|"evidence"|"timeline";title:string;sub:string};
export default function Investigation(){
 const[data,setData]=useState<any>();const[selected,setSelected]=useState<S|null>(null);const[q,setQ]=useState("");const[m,setM]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[generating,setGenerating]=useState(false);const[theory,setTheory]=useState("");const[result,setResult]=useState<any>();const[tab,setTab]=useState("evidence");const[error,setError]=useState("");
 const[sessionId,setSessionId]=useState("");const[notes,setNotes]=useState("");const[pins,setPins]=useState<string[]>([]);const[links,setLinks]=useState<[string,string][]>([]);
 async function loadCase(caseId?:string){setError("");const age=localStorage.getItem("parwande-age")||"13";const id=caseId||localStorage.getItem("parwande-case-id")||"";const url=id?"/api/case?caseId="+encodeURIComponent(id):"/api/case?age="+encodeURIComponent(age);try{const r=await fetch(url,{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error||"پرونده بارگذاری نشد");setData(j);localStorage.setItem("parwande-case-id",j.case.id)}catch(e:any){setError(e.message||"خطا در بارگذاری پرونده")}}
 useEffect(()=>{let sid=localStorage.getItem("parwande-session");if(!sid){sid=crypto.randomUUID();localStorage.setItem("parwande-session",sid)}setSessionId(sid);const saved=localStorage.getItem("parwande-board");if(saved)try{const x=JSON.parse(saved);setPins(Array.isArray(x.pins)?x.pins:[]);setLinks(Array.isArray(x.links)?x.links:[]);setNotes(typeof x.notes==="string"?x.notes:"")}catch{}loadCase()},[]);
 useEffect(()=>{localStorage.setItem("parwande-board",JSON.stringify({pins,links,notes}))},[pins,links,notes]);
 async function newCase(){if(generating)return;const age=Number(localStorage.getItem("parwande-age")||13);setGenerating(true);setError("");try{const r=await fetch("/api/new-case",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({age,difficulty:"کارآگاه"})});const j=await r.json();if(!r.ok)throw Error(j.error||"ساخت پرونده ناموفق بود");localStorage.setItem("parwande-case-id",j.case.id);localStorage.removeItem("parwande-board");setPins([]);setLinks([]);setNotes("");setSelected(null);setM([]);setResult(null);setTheory("");await loadCase(j.case.id)}catch(e:any){setError(e.message||"ساخت پرونده ناموفق بود")}finally{setGenerating(false)}}
 async function loadChat(s:S){setSelected(s);setM([]);if(!sessionId)return;const r=await fetch(`/api/interrogate?sessionId=${encodeURIComponent(sessionId)}&suspectId=${s.id}`,{cache:"no-store"});if(r.ok){const j=await r.json();setM(j.messages||[])}}
 async function ask(){if(!q.trim()||!selected||busy)return;const x=q.trim();setQ("");setBusy(true);try{const r=await fetch("/api/interrogate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({suspectId:selected.id,question:x,sessionId})});const j=await r.json();if(!r.ok)throw Error(j.error||"پاسخ دریافت نشد");setM(j.messages||[...m,{role:"user",content:x},{role:"assistant",content:j.answer||""}])}catch(e:any){setM(v=>[...v,{role:"assistant",content:e.message||"خطا در بازجویی"}])}finally{setBusy(false)}}
 async function submit(){if(!theory.trim()||!data?.case?.id)return;try{const r=await fetch("/api/submit-theory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({theory,caseId:data.case.id})});const j=await r.json();if(!r.ok)throw Error(j.error||"داوری نظریه ناموفق بود");setResult(j)}catch(e:any){setError(e.message||"داوری نظریه ناموفق بود")}}
 if(error&&!data)return <main className="investigation"><div className="errorScreen"><h2>پرونده باز نشد</h2><p>{error}</p><button type="button" className="btn" onClick={()=>loadCase()}>تلاش دوباره</button></div></main>;
 if(!data)return <main className="investigation"><div className="loading">در حال باز کردن پرونده...</div></main>;
 const nodes:Node[]=[...data.suspects.map((s:S)=>({id:"s:"+s.id,type:"suspect",title:s.name,sub:s.role})),...data.evidence.map((e:E)=>({id:"e:"+e.id,type:"evidence",title:e.title,sub:e.importance})),...data.timeline.map((t:T)=>({id:"t:"+t.id,type:"timeline",title:t.title,sub:t.event_time}))];
 function pin(id:string){setPins(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 function connect(id:string){const last=pins[pins.length-1];if(last&&last!==id&&!links.some(([a,b])=>(a===last&&b===id)||(a===id&&b===last)))setLinks(v=>[...v,[last,id]]);if(!pins.includes(id))setPins(v=>[...v,id])}
 return <main className="investigation"><header className="topbar"><div><div className="tag">CASE FILE · پرونده فعال</div><h1>{data.case.title}</h1></div><div className="topActions"><button type="button" className="newCaseBtn" disabled={generating} onClick={newCase}>{generating?"در حال ساخت پرونده…":"＋ پرونده جدید با AI"}</button><div className="status">● تحقیق در جریان</div></div></header>
 {error&&<div className="inlineError">{error}<button type="button" onClick={()=>setError("")}>×</button></div>}
 <nav className="tabs">{[["evidence","📁 مدارک"],["timeline","⏱ خط زمانی"],["board","🧩 برد کارآگاه"],["theory","🧠 نظریه من"]].map(([id,label])=><button type="button" key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <div className="workspace"><aside className="panel suspects"><h2>مظنون‌ها</h2>{data.suspects.map((s:S)=><button type="button" className={"suspect "+(selected?.id===s.id?"selected":"")} key={s.id} onClick={()=>loadChat(s)}><b>{s.name}</b><small>{s.role}</small></button>)}</aside>
 <section className="center">
 {tab==="evidence"&&<div className="panel"><div className="panelHead"><h2>مدارک پرونده</h2><span>{data.evidence.length} مورد</span></div><div className="evidenceGrid">{data.evidence.map((e:E)=><article className={"evidence "+e.importance} key={e.id}><div className="evidenceIcon">✦</div><h3>{e.title}</h3><p>{e.description}</p></article>)}</div></div>}
 {tab==="timeline"&&<div className="panel timeline"><h2>خط زمانی</h2>{data.timeline.map((t:T)=><div className="timeItem" key={t.id}><strong>{t.event_time}</strong><div><b>{t.title}</b><p>{t.description}</p></div></div>)}</div>}
 {tab==="board"&&<div className="panel board"><div className="panelHead"><h2>برد کارآگاه 🧩</h2><button type="button" className="mini" onClick={()=>{setPins([]);setLinks([])}}>پاک‌سازی اتصال‌ها</button></div><p className="muted">روی «پین» بزن تا سرنخ را نگه داری؛ بعد «اتصال» را بزن تا رابطه بین دو سرنخ ثبت شود.</p><div className="boardGrid">{nodes.map(n=><article key={n.id} className={"boardCard "+(pins.includes(n.id)?"pinned":"")}><div><span className="nodeType">{n.type==="suspect"?"مظنون":n.type==="evidence"?"مدرک":"زمان"}</span><h3>{n.title}</h3><small>{n.sub}</small></div><div className="nodeActions"><button type="button" onClick={()=>pin(n.id)}>{pins.includes(n.id)?"📌 پین شد":"📍 پین"}</button><button type="button" onClick={()=>connect(n.id)}>🔗 اتصال</button></div></article>)}</div><h3 className="sectionTitle">اتصال‌های ثبت‌شده</h3>{links.length===0?<div className="empty">هنوز اتصالی ثبت نشده.</div>:<div className="connections">{links.map(([a,b],i)=>{const A=nodes.find(n=>n.id===a),B=nodes.find(n=>n.id===b);return <div className="connection" key={i}><b>{A?.title}</b><span>↔</span><b>{B?.title}</b><button type="button" onClick={()=>setLinks(v=>v.filter((_,j)=>j!==i))}>×</button></div>})}</div>}<h3 className="sectionTitle">یادداشت‌های کارآگاه</h3><textarea className="boardNotes" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="نکته‌ها، تناقض‌ها و حدس‌هایت را اینجا بنویس..." /></div>}
 {tab==="theory"&&<div className="panel theory"><h2>نظریه کارآگاه</h2><p className="muted">چه کسی مسئول است؟ چه اتفاقی افتاد؟ و چه مدارکی نظریه‌ات را ثابت می‌کنند؟</p><textarea value={theory} onChange={e=>setTheory(e.target.value)} placeholder="نظریه‌ات را با جزئیات بنویس..." /><button type="button" className="btn" onClick={submit}>تحویل نظریه 🔎</button>{result&&<div className="result"><h3>{result.verdict==="correct"?"پرونده حل شد 🎯":result.verdict==="partial"?"بخشی از حقیقت را پیدا کردی":"هنوز چند تکه مهم گم شده"}</h3><div className="score">{result.score}/100</div><p>{result.explanation}</p>{result.correct_points?.length>0&&<><b>نکات درست</b><ul>{result.correct_points.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></>}{result.missing_points?.length>0&&<><b>موارد ناقص</b><ul>{result.missing_points.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></>}</div>}</div>}
 </section><aside className="panel interrogation"><h2>بازجویی</h2>{!selected?<div className="empty">یک مظنون را انتخاب کن و سؤال بپرس.</div>:<><div className="suspectHero"><div className="avatar">{selected.name[0]}</div><div><b>{selected.name}</b><small>{selected.role}</small></div></div><div className="chat">{m.length===0&&<div className="hint">سؤال بپرس؛ پاسخ‌ها در همین پرونده ذخیره می‌شوند.</div>}{m.map((x,i)=><div key={i} className={"bubble "+x.role}>{x.content}</div>)}{busy&&<div className="bubble suspect">در حال پاسخ دادن…</div>}</div><div className="ask"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="مثلاً: ساعت ۲۳:۴۰ کجا بودی؟"/><button type="button" onClick={ask} disabled={busy||!q.trim()}>ارسال</button></div></>}</aside></div></main>
}